//! `brain install-hooks` — generate Claude Code hooks for transparent context injection.
//!
//! Writes `.claude/hooks/{pre_prompt.sh, post_response.sh}`, copies the Node
//! client into `.brain/brain-client.mjs`, and registers the hooks in
//! `.claude/settings.json` (merging, never clobbering existing settings).
//!
//! Running the command a second time is a no-op (idempotent).

use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use brain_core::paths::ProjectPaths;
use brain_core::scaffold;
use brain_core::{BrainError, Result};

/// The Node client source, embedded at compile time so the installed project
/// is self-contained (no dependency on where brain-engine is checked out).
const CLIENT_SRC: &str = include_str!("../../../../clients/node/brain-client.mjs");

pub fn run(root: &Path, json: bool) -> Result<()> {
    let paths = ProjectPaths::new(root.to_path_buf());

    // Ensure the project is initialised (idempotent) so the daemon can start later.
    if !paths.is_initialised() {
        scaffold::init(root)?;
    }

    // 1. Copy the embedded Node client into .brain/ (gitignored, always regenerable).
    let client_path = paths.brain_dir().join("brain-client.mjs");
    std::fs::create_dir_all(paths.brain_dir()).map_err(|e| BrainError::io(paths.brain_dir(), e))?;
    std::fs::write(&client_path, CLIENT_SRC).map_err(|e| BrainError::io(&client_path, e))?;

    // 2. Write the two hook scripts (executable, mode 0755).
    let hooks_dir = root.join(".claude").join("hooks");
    std::fs::create_dir_all(&hooks_dir).map_err(|e| BrainError::io(&hooks_dir, e))?;

    let pre = hooks_dir.join("pre_prompt.sh");
    let post = hooks_dir.join("post_response.sh");
    write_exec(&pre, &pre_prompt_script(&client_path))?;
    write_exec(&post, &post_response_script(&client_path))?;

    // 3. Merge hook registration into .claude/settings.json (preserves existing keys).
    let settings_path = root.join(".claude").join("settings.json");
    let updated = merge_settings(&settings_path)?;

    if json {
        println!(
            "{}",
            serde_json::json!({
                "status":           "installed",
                "pre_prompt":       pre,
                "post_response":    post,
                "client":           client_path,
                "settings_updated": updated,
            })
        );
    } else {
        println!("✓ Brain hooks installed for {}", root.display());
        println!("  + {}", pre.display());
        println!("  + {}", post.display());
        println!("  + {}", client_path.display());
        if updated {
            println!("  • registered UserPromptSubmit + Stop in .claude/settings.json");
        } else {
            println!("  • settings.json already up to date (no changes needed)");
        }
        println!("\nClaude Code will now inject retrieved context automatically.");
        println!("The daemon is started on-demand on the first prompt.");
        println!("\nEconomic output styles (installed globally by ./install.sh) — pick one per");
        println!("project in Claude Code via /config → Output style:");
        println!("  • Brain Eco        — terse prose, minimal code, token-saving");
        println!("  • Brain Eco Ultra  — maximum compression, code-first answers");
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Hook script generators
// ---------------------------------------------------------------------------

fn pre_prompt_script(client: &Path) -> String {
    format!(
        r#"#!/usr/bin/env bash
# Generated by `brain install-hooks` — UserPromptSubmit hook.
# Reads the event JSON on stdin, ensures the daemon is up, injects context.
set -euo pipefail
ROOT="${{CLAUDE_PROJECT_DIR:-$PWD}}"
CLIENT="{client}"
command -v node >/dev/null 2>&1 || exit 0   # no node → silent no-op
EVENT="$(cat)"
# Best-effort bootstrap: start the daemon if it is not responding.
if ! echo "$EVENT" | BRAIN_ROOT="$ROOT" node "$CLIENT" ping >/dev/null 2>&1; then
  brain --path "$ROOT" daemon start >/dev/null 2>&1 || true
fi
echo "$EVENT" | BRAIN_ROOT="$ROOT" node "$CLIENT" hook-prompt 2>/dev/null || true
"#,
        client = client.display()
    )
}

fn post_response_script(client: &Path) -> String {
    format!(
        r#"#!/usr/bin/env bash
# Generated by `brain install-hooks` — Stop hook.
# Reads the event JSON on stdin and stores the assistant response in the cache.
set -euo pipefail
ROOT="${{CLAUDE_PROJECT_DIR:-$PWD}}"
CLIENT="{client}"
command -v node >/dev/null 2>&1 || exit 0
cat | BRAIN_ROOT="$ROOT" node "$CLIENT" hook-stop 2>/dev/null || true
"#,
        client = client.display()
    )
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn write_exec(path: &Path, contents: &str) -> Result<()> {
    std::fs::write(path, contents).map_err(|e| BrainError::io(path, e))?;
    let mut perms = std::fs::metadata(path)
        .map_err(|e| BrainError::io(path, e))?
        .permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms).map_err(|e| BrainError::io(path, e))?;
    Ok(())
}

/// Idempotently add our hook commands to `settings.json`, preserving existing keys.
/// Returns `true` if the file changed.
fn merge_settings(path: &Path) -> Result<bool> {
    use serde_json::{json, Value};

    let mut root_val: Value = if path.exists() {
        let txt = std::fs::read_to_string(path).map_err(|e| BrainError::io(path, e))?;
        serde_json::from_str(&txt).unwrap_or_else(|_| json!({}))
    } else {
        json!({})
    };

    if !root_val.is_object() {
        root_val = json!({});
    }

    // root_val is guaranteed to be an object by the checks above.
    let root_obj = root_val
        .as_object_mut()
        .expect("root_val is always an object at this point");
    let hooks = root_obj.entry("hooks").or_insert_with(|| json!({}));
    if !hooks.is_object() {
        *hooks = json!({});
    }

    let mut changed = false;
    let entries = [
        (
            "UserPromptSubmit",
            "$CLAUDE_PROJECT_DIR/.claude/hooks/pre_prompt.sh",
        ),
        ("Stop", "$CLAUDE_PROJECT_DIR/.claude/hooks/post_response.sh"),
    ];

    for (event, cmd) in entries {
        // hooks is guaranteed to be an object by the check above.
        let arr = hooks
            .as_object_mut()
            .expect("hooks is always an object at this point")
            .entry(event)
            .or_insert_with(|| json!([]));
        if !arr.is_array() {
            *arr = json!([]);
        }
        // Skip if any matcher group already contains our command (idempotent).
        // arr is guaranteed to be an array by the check above.
        let already = arr
            .as_array()
            .expect("arr is always an array at this point")
            .iter()
            .any(|group| {
                group
                    .get("hooks")
                    .and_then(|h| h.as_array())
                    .is_some_and(|hs| {
                        hs.iter()
                            .any(|h| h.get("command").and_then(|c| c.as_str()) == Some(cmd))
                    })
            });
        if !already {
            arr.as_array_mut()
                .expect("arr is always an array at this point")
                .push(json!({
                    "hooks": [ { "type": "command", "command": cmd } ]
                }));
            changed = true;
        }
    }

    if changed || !path.exists() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| BrainError::io(parent, e))?;
        }
        let out = serde_json::to_string_pretty(&root_val)? + "\n";
        std::fs::write(path, out).map_err(|e| BrainError::io(path, e))?;
    }
    Ok(changed)
}
